eureka:
  client:
    register-with-eureka:
      value: false;
    fetch-registry:
      value: false;
    service-url:
      defaultZone: http://52.221.242.180:8761/eureka
    instance:
      hostname: aws-host

