eureka:
  instance:
    leaseRenewalIntervalInSeconds: 28
    leaseExpirationDurationInSeconds: 1
    prefer-ip-address: true
    ip-address: 54.255.187.169 
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://3.0.100.17/eureka
    instance:
      hostname: aws-host

